name: CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1

            - name: yarn install
              run: |
                  yarn install
              env:
                  CI: true

            - name: yarn build
              run: |
                  yarn run build --if-present

            - name: Add remote origin
              run: |
                  git remote add heroku https://heroku:${{ secrets.API_KEY }}@git.heroku.com/${{ secrets.APP_NAME }}.git
            - name: Deploy to Heroku
              run: |
                  git push heroku HEAD:master -f
